EgitimMerkezi/Areas/Admin/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EgitimMerkezi.Areas.Admin.Controllers
{
    public class SliderController : Controller
    {
        EgitimMerkeziEntities db = new EgitimMerkeziEntities();
        // GET: Admin/Slider
        public ActionResult Index()
        {
            var model = db.Slider.OrderByDescending(x => x.ID).ToList();
            return View(model);
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult AddSlider(Slider model)
        {
            if (ModelState.IsValid)
            {
                db.Slider.Add(model);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

EgitimMerkezi/Areas/Admin/Views/Slider/Add.cshtml
@model EgitimMerkezi.Slider

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div id="page-heading">
    <ol class="breadcrumb">
        <li><a href="index.htm">Dashboard</a></li>
        <li>UI Elements</li>
        <li class="active">Tables</li>
    </ol>

    <h1>Yeni Slider Ekleme</h1>
    <div class="options">
        <div class="btn-toolbar">
            <div class="btn-group hidden-xs">
                <a href='#' class="btn btn-default dropdown-toggle" data-toggle='dropdown'><i class="fa fa-cloud-download"></i><span class="hidden-sm"> Export as  </span><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Text File (*.txt)</a></li>
                    <li><a href="#">Excel File (*.xlsx)</a></li>
                    <li><a href="#">PDF File (*.pdf)</a></li>
                </ul>
            </div>
            <a href="#" class="btn btn-default"><i class="fa fa-cog"></i></a>
        </div>
    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4>Form Layout</h4>

                </div>
                @using (Html.BeginForm("AddSlider", "Slider", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <div class="panel-body">
                        <h3>Basic Form Elements</h3>
                        <p>Try resizing the window to see how the form adapts at smaller screen sizes!</p>
                        <br>

                        <div class="form-group">
                            @Html.LabelFor(m => m.SliderText, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.SliderText, new { @class = "form-control", placeholder = "Slider Yazısı" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.BaslangicTarih, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.BaslangicTarih, new { @class = "form-control", placeholder = "Başlangıç Tarihi" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.BitisTarih, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.BitisTarih, new { @class = "form-control", placeholder = "Bitiş Tarihi" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.ResimYolu, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.ResimYolu, new { @class = "form-control", placeholder = "Resim Yolu" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>

                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <div class="btn-toolbar">
                                    <button class="btn-primary btn">Submit</button>
                                    <button class="btn-default btn">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section jsplugins
{
    <script type='text/javascript' src='~/assets/plugins/codeprettifier/prettify.js'></script>
    <script type='text/javascript' src='~/assets/plugins/easypiechart/jquery.easypiechart.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/sparklines/jquery.sparklines.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-toggle/toggle.min.js'></script>
}

EgitimMerkezi/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div id="page-heading">
    <ol class="breadcrumb">
        <li><a href="index.htm">Dashboard</a></li>
        <li>UI Elements</li>
        <li class="active">Tables</li>
    </ol>

    <h1>Tables</h1>
    <div class="options">
        <div class="btn-toolbar">
            <div class="btn-group hidden-xs">
                <a href='#' class="btn btn-default dropdown-toggle" data-toggle='dropdown'><i class="fa fa-cloud-download"></i><span class="hidden-sm"> Export as  </span><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Text File (*.txt)</a></li>
                    <li><a href="#">Excel File (*.xlsx)</a></li>
                    <li><a href="#">PDF File (*.pdf)</a></li>
                </ul>
            </div>
            <a href="#" class="btn btn-default"><i class="fa fa-cog"></i></a>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4>Slider Tablosu</h4>
                    <div class="options">

                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Başlangıç Tarihi</th>
                                <th>Bitiş Tarihi</th>
                                <th>Text</th>
                                <th>Resim Yolu</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.BaslangicTarih</td>
                                    <td>@item.BitisTarih</td>
                                    <td>@item.SliderText</td>
                                    <td>@item.ResimYolu</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>